# Generated by Django 3.0.5 on 2020-09-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('Date_of_entry', models.DateField(max_length=8)),
                ('Child_Fname', models.CharField(max_length=200, null=True)),
                ('Child_Lname', models.CharField(max_length=200, null=True)),
                ('Date_of_birth', models.DateField(max_length=8)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('Relegion', models.CharField(max_length=200, null=True)),
                ('Caste', models.CharField(max_length=200, null=True)),
                ('Father_name', models.CharField(max_length=200, null=True)),
                ('Mother_name', models.CharField(max_length=200, null=True)),
                ('Siblings', models.IntegerField(null=True)),
                ('Contact_Number', models.IntegerField(blank=True, null=True)),
                ('Name_of_sponsor', models.CharField(max_length=200, null=True)),
                ('Need_of_child', models.CharField(max_length=200, null=True)),
                ('Join_date_of_diksha', models.DateField(max_length=8)),
                ('Children_came_diksha', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_of_child', models.CharField(max_length=120, null=True)),
                ('Fname', models.CharField(max_length=120, null=True)),
                ('Sname', models.CharField(max_length=120, null=True)),
                ('Nationality', models.CharField(max_length=120, null=True)),
                ('Contact_Number', models.CharField(max_length=120, null=True)),
                ('Email', models.CharField(max_length=120, null=True)),
                ('Address', models.CharField(max_length=120, null=True)),
                ('Sponsorship_for', models.CharField(max_length=120, null=True)),
                ('Date_of_payment', models.CharField(max_length=120, null=True)),
                ('Name_of_sponsor_kid', models.CharField(max_length=120, null=True)),
                ('Sponsor_met_the_children', models.CharField(max_length=120, null=True)),
                ('Plan_to_meet', models.CharField(max_length=120, null=True)),
                ('Standing_monthly_order', models.CharField(max_length=120, null=True)),
                ('Standing_yearly_order', models.CharField(max_length=120, null=True)),
                ('Sponsor_stopped_to_pay', models.CharField(max_length=120, null=True)),
                ('Which_date', models.CharField(max_length=120, null=True)),
                ('Reason', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
