# Generated by Django 3.0.5 on 2020-09-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='id',
        ),
        migrations.AddField(
            model_name='children',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Accomodation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Board',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Child_goes_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Child_studying_from',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Class',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='College_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Fees_for_accomodation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Hostel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Hostel_Fees',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Level_of_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Medium',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Scheme_of_course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='School_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Semeste',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Type_of_College',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Type_of_school',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='University',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='code',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='Code_of_child',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
