# Generated by Django 3.0.5 on 2020-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0002_auto_20200926_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='Bank_account',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
