# Generated by Django 3.0.5 on 2020-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0003_sponsor_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='Code_of_child',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
