# Generated by Django 3.0.5 on 2020-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0004_auto_20200926_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
